name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      # Log in to Docker Hub or your container registry if needed
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag file:$(date +%s

      # Push the built image to Docker Hub or your container registry
      # - name: Push Docker image to Docker Hub
      #   run: |
      #     docker push my-image-name:$(date +%s)
